steps:
  # Step 1: Build the Docker image for the API
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - '/Dockerfile'  # Specify the custom Dockerfile location here
      - '-t'
      - 'gcr.io/sinuous-origin-452313-p2/github.com/lukski175/minitwit-fs:dockerimage-API'
      - '.'
    id: 'Build API Docker Image'

# Substitutions (this is optional)
substitutions:
  _REGION: 'europe-west1'
  _SERVICE_NAME: 'minitwitapi'

timeout: '1200s' # Optional, increase timeout if needed

options:
  logging: CLOUD_LOGGING_ONLY