steps:
  # Step 1: Build the Docker image for the API
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'MiniTwitAPI/Dockerfile'  # Specify the custom Dockerfile location here
      - '-t'
      - 'gcr.io/sinuous-origin-452313-p2/github.com/lukski175/minitwit-fs:dockerimage-API$COMMIT_SHA'
      - '.'
    id: 'Build API Docker Image'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/sinuous-origin-452313-p2/github.com/lukski175/minitwit-fs:dockerimage-API$COMMIT_SHA'
    id: 'Push API Docker Image'

  # Step 3: Deploy the Docker image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'  # Cloud Run service name from substitutions
      - '--image'
      - 'gcr.io/sinuous-origin-452313-p2/github.com/lukski175/minitwit-fs:dockerimage-API$COMMIT_SHA'
      - '--region'
      - '${_REGION}'  # Cloud region from substitutions
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Optional: Allows public access to your service
    id: 'Deploy to Cloud Run'

# Substitutions (this is optional)
substitutions:
  _REGION: 'europe-west1'
  _SERVICE_NAME: 'minitwitapi'

timeout: '1200s'  # Optional, increase timeout if needed

options:
  logging: CLOUD_LOGGING_ONLY
