name: Build and Commit Web Client

on:
  push:
    branches:
      - main
    paths:
      - 'MiniTwitClient/**'  # Only trigger when something inside this folder changes

jobs:
  build:
    if: github.actor != 'github-actions[bot]'  # Prevent infinite loops
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./MiniTwitClient/MiniTwitClient.csproj

      - name: Remove existing dist folder if it exists
        run: |
          if (Test-Path ./MiniTwitClient/dist) {
            Remove-Item -Recurse -Force ./MiniTwitClient/dist
          }
        shell: pwsh

      - name: Build project
        run: |
          $env:NODE_ENV="prod"
          dotnet publish ./MiniTwitClient -c Release -r win-x64 -o ./MiniTwitClient/dist
        shell: pwsh

      - name: Check if main branch has changed
        run: |
          git fetch origin main
          $localHash = git rev-parse HEAD
          $remoteHash = git rev-parse origin/main
          if ($localHash -ne $remoteHash) {
            Write-Output "Remote main has new commits. Aborting to avoid conflicts."
            exit 1
          }
        shell: pwsh

      - name: Commit and push dist folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add MiniTwitClient/dist
          git commit -m "Auto-build client and update dist folder"
          git push origin main
        shell: pwsh

      - name: Trigger deploy-client workflow
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy-client
