name: Build PDF Report (LaTeX)

on:
  push:
    branches:
      - main
    paths:
      - 'report/**'
      - '.github/workflows/build-report.yml'

jobs:
  build-pdf:
    if: github.actor != 'github-actions[bot]'  # Prevent infinite loops
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure build directory exists
        run: mkdir -p report/build

      - name: Build LaTeX report
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: report/src
          output_directory: ../build  # relative to working_directory, so this is report/build

      - name: Check output
        run: ls -la report/build

      - name: Commit and push generated PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add report/build/main.pdf
          git diff --cached --quiet || git commit -m "Auto-build PDF report"
          git push
