name: Build PDF Report (LaTeX)

on:
  push:
    branches: [ main ]
    paths:
      - 'report/**'
      - '.github/workflows/build-report.yml'

# 1 – let the runner push or upload artefacts
permissions:
  contents: write

jobs:
  build-pdf:
    if: github.actor != 'github-actions[bot]'   # avoid loops
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4       # v4 = faster shallow-clone

      # 2 – compile the TeX document
      - name: Compile LaTeX → PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: report/src
          output_directory: ../build      # => report/build/main.pdf
          # uncomment if your project needs XeLaTeX or shell-escape, etc.
          # latexmk_use_xelatex: true
          # latexmk_shell_escape: true
          # extra_system_packages: "make pygments"

      # 3 – expose the PDF in the workflow’s “Artifacts” tab
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiniTwit-report # how it appears in the UI
          path: report/build/main.pdf

      # 4 – OPTIONAL: commit the generated PDF back to the repo
      # - name: Commit and push generated PDF
      #   run: |
      #     git config user.name  "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add report/build/main.pdf
      #     git commit -m "CI: auto-build PDF [skip ci]" || exit 0
      #     git push
