name: Build PDF report

on:
  push:
    branches: [main]
    paths:
      - 'report/**'
      - '.github/workflows/build-report.yml'

permissions:
  contents: write          # only needed if you later push the PDF back

jobs:
  pdf:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1.  Create the build folder once per run
      - name: Prepare build directory
        run: mkdir -p report/build

      # 2.  Compile; -outdir is relative to working_directory (report/src)
      - name: Compile LaTeX into build/
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: report/src
          args: -pdf -interaction=nonstopmode -halt-on-error -file-line-error -outdir=../build

      # 3.  Upload the generated PDF
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiniTwit-PDF
          path: report/build/main.pdf
