name: Build PDF report

on:
  push:
    branches: [main]
    paths:
      - 'report/**'
      - '.github/workflows/build-report.yml'

permissions:               # let the runner write or upload
  contents: write

jobs:
  pdf:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex            # file is in report/src/
          working_directory: report/src  # <— no output_directory key

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiniTwit-PDF
          path: report/src/main.pdf      # where latexmk really wrote it

      # OPTIONAL – commit the PDF back to the repo
      # - name: Commit generated PDF
      #   if: github.ref == 'refs/heads/main'
      #   run: |
      #     git config --global user.name  'github-actions[bot]'
      #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      #     git add report/src/main.pdf
      #     git diff --cached --quiet || git commit -m "CI: update report PDF [skip ci]"
      #     git push
