name: Build Web Client

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore ./MiniTwitClient/MiniTwitClient.csproj

      - name: Remove existing dist folder
        run: Remove-Item -Recurse -Force ./MiniTwitClient/dist
        shell: pwsh

      - name: Build project
        run: |
          $env:NODE_ENV="prod"
          dotnet publish ./MiniTwitClient -c Release -r win-x64 -o ./MiniTwitClient/dist
        shell: pwsh
