name: Build PDF report

on:
  push:
    branches: [main]
    paths:
      - 'report/**'
      - '.github/workflows/build-report.yml'

permissions:
  contents: write          # only needed if you later push the PDF back

jobs:
  pdf:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1.  Create the build folder once per run
      - name: Prepare build directory
        run: mkdir -p report/build

      # 2.  Compile; -outdir is relative to working_directory (report/src)
      - name: Compile LaTeX into build/
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: report/src
          args: -pdf -interaction=nonstopmode -halt-on-error -file-line-error -outdir=../build

      # 3.  Upload the generated PDF
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:

      - name: Commit generated PDF
        if: github.ref == 'refs/heads/main'          # only from main
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # stage or replace the file
          git add report/build/main.pdf

          # skip commit if nothing changed
          git diff --cached --quiet && exit 0

          git commit -m "CI: update report PDF [skip ci]"
          git push
    name: MiniTwit-PDF
          path: report/build/main.pdf
